services:
  weather-collector:
    container_name: weather-collector
    build: 
      context: weather-collector
  backend:
    container_name: backend
    build:
      context: backend
    networks:
      - default
      - frontend
    ports:
      - 8000:8000
  redis-cache:
    container_name: redis-cache
    image: redis/redis-stack-server:latest
  frontend:
    container_name: frontend
    build:
      context: frontend
    networks:
      - frontend
    ports:
      - 3002:4000

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"