services:
  weather-collector:
    container_name: weather-collector
    build: 
      context: weather-collector
    restart: unless-stopped
  backend:
    container_name: weather-backend
    build:
      context: backend
    networks:
      - default
      - frontend
    ports:
      - 8001:8001
      - 8002:8002
    restart: unless-stopped
  redis-cache:
    container_name: redis-cache
    image: redis/redis-stack-server:latest
    restart: unless-stopped
  frontend:
    container_name: weather-frontend
    build:
      context: frontend
    networks:
      - frontend
    ports:
      - 4000:3002
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"